site_name: 分享会

repo_name: 分享会
repo_url: https://github.com/smxm/HUTshares

nav:
  - 导航: index.md
  - 第一期:
    - 检索: 第一期/检索.md
    - 开场: 第一期/开场.md
    - PPT: 第一期/PPT.md
theme:
  name: material
  custom_dir: overrides
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/smxm/HUTshares
  analytics:
    provider: google
    property: G-KJB4RXSKZG